s=set()
n=input("Enter a number 1: ")
s.add(int(n))
n=input("Enter a number 2: ")
s.add(int(n))
n=input("Enter a number 3: ")
s.add(int(n))
n=input("Enter a number 4: ")
s.add(int(n))
n=input("Enter a number 5: ")
s.add(int(n))
n=input("Enter a number 6: ")
s.add(int(n))
n=input("Enter a number 7: ")
s.add(int(n))
n=input("Enter a number 8: ")
s.add(int(n))

print(s)
